# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        from font_init import init_fonts
        init_fonts()

        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 500)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("background-color: rgb(30, 30, 30);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setStyleSheet("QWidget {\n"
"    background-color: rgb(39, 39, 39);\n"
"    color: rgb(230, 230, 230);\n"
"    border-radius: 5px;\n"
"    font: 16pt \"Ermilov\";\n"
"}\n"
"\n"
"QPushButton {\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    background-color: rgba(212, 170, 125, 255);\n"
"    color: rgb(230, 230, 230);\n"
"    border-radius: 5px;\n"
"    font: 16pt \"Ermilov\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    background-color: rgba(239, 208, 158, 230);\n"
"    color: rgb(230, 230, 230);\n"
"    border-radius: 5px;\n"
"    font: 16pt \"Ermilov\";\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    background-color: rgba(239, 208, 158, 230);\n"
"    color: rgb(230, 230, 230);\n"
"    border-radius: 5px;\n"
"    font: 16pt \"Ermilov\";\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(-1, 9, -1, 9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("QLabel {\n"
"    font: 12pt \"Ermilov\";\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.disc_space_button = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disc_space_button.sizePolicy().hasHeightForWidth())
        self.disc_space_button.setSizePolicy(sizePolicy)
        self.disc_space_button.setMinimumSize(QtCore.QSize(0, 60))
        self.disc_space_button.setCheckable(True)
        self.disc_space_button.setChecked(True)
        self.disc_space_button.setAutoExclusive(True)
        self.disc_space_button.setObjectName("disc_space_button")
        self.horizontalLayout_2.addWidget(self.disc_space_button)
        self.processes_button = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processes_button.sizePolicy().hasHeightForWidth())
        self.processes_button.setSizePolicy(sizePolicy)
        self.processes_button.setMinimumSize(QtCore.QSize(0, 60))
        self.processes_button.setCheckable(True)
        self.processes_button.setAutoExclusive(True)
        self.processes_button.setObjectName("processes_button")
        self.horizontalLayout_2.addWidget(self.processes_button)
        self.autorun_button = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autorun_button.sizePolicy().hasHeightForWidth())
        self.autorun_button.setSizePolicy(sizePolicy)
        self.autorun_button.setMinimumSize(QtCore.QSize(0, 60))
        self.autorun_button.setCheckable(True)
        self.autorun_button.setAutoExclusive(True)
        self.autorun_button.setObjectName("autorun_button")
        self.horizontalLayout_2.addWidget(self.autorun_button)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scroll_clear = QtWidgets.QScrollArea(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_clear.sizePolicy().hasHeightForWidth())
        self.scroll_clear.setSizePolicy(sizePolicy)
        self.scroll_clear.setStyleSheet("QScrollBar:vertical {\n"
"    background-color: rgb(39, 39, 39);\n"
"    width: 15px;\n"
"    border-radius: 0px;\n"
"    border: 0px solid rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: none;\n"
"    background-color: rgb(239, 208, 158);;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    background: none;\n"
"    border: 0px solid white;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"    border: 0px solid white;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: rgb(39, 39, 39);\n"
"    color: rgb(230, 230, 230);\n"
"    border-radius: 5px;\n"
"    font: 16pt \"Ermilov\";\n"
"}\n"
"\n"
"QCheckBox {\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 53px;\n"
"    height: 53px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(:/icons/rec/switch_off.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(:/icons/rec/switch_on.png);\n"
"}\n"
"")
        self.scroll_clear.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scroll_clear.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scroll_clear.setLineWidth(0)
        self.scroll_clear.setWidgetResizable(True)
        self.scroll_clear.setObjectName("scroll_clear")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 765, 359))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("QLabel {\n"
"    font: 12pt \"Ermilov\";\n"
"}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.temp_clear = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.temp_clear.setObjectName("temp_clear")
        self.verticalLayout_3.addWidget(self.temp_clear)
        self.downloads_clear = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.downloads_clear.setObjectName("downloads_clear")
        self.verticalLayout_3.addWidget(self.downloads_clear)
        self.desktop_clear = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desktop_clear.sizePolicy().hasHeightForWidth())
        self.desktop_clear.setSizePolicy(sizePolicy)
        self.desktop_clear.setObjectName("desktop_clear")
        self.verticalLayout_3.addWidget(self.desktop_clear)
        self.autorun_clear = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.autorun_clear.setObjectName("autorun_clear")
        self.verticalLayout_3.addWidget(self.autorun_clear)
        self.processes_clear = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.processes_clear.setObjectName("processes_clear")
        self.verticalLayout_3.addWidget(self.processes_clear)
        self.spacing_clear = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.spacing_clear.setText("")
        self.spacing_clear.setObjectName("spacing_clear")
        self.verticalLayout_3.addWidget(self.spacing_clear)
        self.scroll_clear.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scroll_clear)
        self.run_clear = QtWidgets.QPushButton(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_clear.sizePolicy().hasHeightForWidth())
        self.run_clear.setSizePolicy(sizePolicy)
        self.run_clear.setMinimumSize(QtCore.QSize(0, 60))
        self.run_clear.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgba(110, 116, 79, 255);\n"
"    color: rgb(230, 230, 230);\n"
"    border-radius: 5px;\n"
"    font: 16pt \"Ermilov\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(110, 116, 79, 190);\n"
"    color: rgb(230, 230, 230);\n"
"    border-radius: 5px;\n"
"    font: 16pt \"Ermilov\";\n"
"}")
        self.run_clear.setCheckable(False)
        self.run_clear.setChecked(False)
        self.run_clear.setAutoExclusive(False)
        self.run_clear.setObjectName("run_clear")
        self.verticalLayout_2.addWidget(self.run_clear)
        self.verticalLayout.addWidget(self.main_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Профили очистки"))
        self.disc_space_button.setText(_translate("MainWindow", "Место на диске"))
        self.processes_button.setText(_translate("MainWindow", "Процессы"))
        self.autorun_button.setText(_translate("MainWindow", "Автозагрузка"))
        self.label_2.setText(_translate("MainWindow", "Настройки очистки"))
        self.temp_clear.setText(_translate("MainWindow", "Очистка папки Temp"))
        self.downloads_clear.setText(_translate("MainWindow", "Очистка загрузок"))
        self.desktop_clear.setText(_translate("MainWindow", "Очистка рабочего стола"))
        self.autorun_clear.setText(_translate("MainWindow", "Очистка автозагрузки"))
        self.processes_clear.setText(_translate("MainWindow", "Оптимизация процессов"))
        self.run_clear.setText(_translate("MainWindow", "Запуск"))
import rec_rc
